apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: uc6fi6io3-nodejs
  janus-idp.io/tekton: uc6fi6io3-nodejs
  backstage.io/kubernetes-id: uc6fi6io3-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: uc6fi6io3-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
