apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: uc6fi6io3-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: uc6fi6io3-nodejs 
  name: uc6fi6io3-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: uc6fi6io3-nodejs 
